project:
  type: website

website:
  title: "DL Paper Reviews"
  description: "딥러닝 논문 리뷰 포트폴리오"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reviews/index.qmd
        text: Reviews
    right:
      - icon: github
        href: https://github.com/Kimgundo58/Paper-Review

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
    highlight-style: github
    math: mathjax
